on: push

jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                version: [master]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: goto-bus-stop/setup-zig@v2
              with:
                version: ${{ matrix.version }}
            - run: zig build test
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: goto-bus-stop/setup-zig@v2
              with:
                version: master
            - run: zig fmt --check src/*.zig